-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Resepti CASCADE;
DROP TABLE IF EXISTS Valmistusvaihe CASCADE;
DROP TABLE IF EXISTS Raaka_aine CASCADE;
DROP TABLE IF EXISTS Ainesosa CASCADE;
